@baseUrl = http://localhost:9000

### Run POST request to create a new animal
POST {{baseUrl}}/data/Animal/Fido

{
    "Name": "Fido the dog",
    "Age": 6,
    "Noise": "Woof"
}

### Run POST request to create a new animal
POST {{baseUrl}}/data/Animal/Mia

{
    "Name": "Mia the cat",
    "Age": 2,
    "Noise": "Meow"
}

### Run POST request to create a new animal
POST {{baseUrl}}/data/Home/Fido

{
    "Description": "Fido's home"    
}

### Run GET request to retrieve animal
GET {{baseUrl}}/data/animal/Fido

### Run GET request to retrieve animal
GET {{baseUrl}}/data/animal/Fido,Mia

### Run GET request to retrieve animal
GET {{baseUrl}}/data/Animal,Home/Fido


### Make noise
POST {{baseUrl}}/data/Animal/Fido/MakeNoise

### Test service
POST {{baseUrl}}/services/Greeter/ShoutHelloTo

"OCore"


### GET to retrieve Fido
GET {{baseUrl}}/data/Animal,Home/Fido

###
POST http://localhost:15420/services/Greeter/SayHelloTo
Accept: application/json
Content-Type: application/json

["OCore"]